#!bin/bash

LOG_DIR="./logs"
BACKUP_DIR="./backups"
mkdir -p "$LOG_DIR" "$BACKUP_DIR"

# --- Utilty Functions ---
pause(){
        read -p "Press [Enter] key to continue..."
}
confirm(){
        read -p "Are you sure? (y/n):" choice
        case "$choice" in
                y|Y) return 0 ;;
                *) echo "Operation cancelled"; return 1 ;;
        esac
}

#--- FILE MANAGMENT FUNCTIONS

create file(){
read -p "Enter file name: " filename
if [-e "$filename"]; then
        echo "File already exists!"
else
        touch "$filename" && echo "File '$filename' created."
fi
pause
}

